# Generated by Django 4.2.10 on 2024-02-11 13:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("phone_number", models.CharField(max_length=20)),
                ("monthly_salary", models.IntegerField(default=0)),
                ("approved_limit", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                 (
                    "customer_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firstapp.customer",
                    ),
                ),
                (
                    "loan_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("loan_amount", models.IntegerField(default=0)),
                ("tenure", models.IntegerField(default=0)),
                ("interest_rate", models.FloatField(default=0)),
                ("monthly_payment", models.IntegerField(default=0)),
                ("emi_paid_on_time", models.IntegerField(default=0)),
                (
                    "start_date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
            ],
        ),
    ]
